// Episode transcripts in various formats for accessibility and search
// See README.md for full design rationale.

import { pgTable, pgEnum, uuid, text, boolean, timestamp, index } from "drizzle-orm/pg-core";
import { episodes } from "./episodes";

export const transcriptFormatEnum = pgEnum("transcript_format_enum", ["srt", "vtt", "json", "text"]);

export const transcripts = pgTable(
  "transcripts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    episodeId: uuid("episode_id").notNull().references(() => episodes.id, { onDelete: "cascade" }),
    format: transcriptFormatEnum("format").notNull(),
    contentUrl: text("content_url"),
    content: text("content"),
    language: text("language").notNull().default("en"),
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_transcripts_episode_id_format_language").on(table.episodeId, table.format, table.language),
  ]
);
