// affiliate_links: Trackable links generated by affiliates with click/conversion counters.
// See README.md for full design rationale.
import { Timestamp } from "firebase/firestore";

/**
 * @typedef {Object} AffiliateLinkDocument
 * @property {string} id
 * @property {string} affiliateId - FK → affiliates
 * @property {string} token
 * @property {string|null} slug
 * @property {string} destinationUrl
 * @property {string|null} label
 * @property {number} totalClicks
 * @property {number} totalConversions
 * @property {boolean} isActive
 * @property {Timestamp} createdAt
 * @property {Timestamp} updatedAt
 */

/**
 * @param {Omit<AffiliateLinkDocument, "id" | "createdAt" | "updatedAt">} data
 * @returns {Omit<AffiliateLinkDocument, "id">}
 */
export function createAffiliateLink(data) {
  return {
    affiliateId:      data.affiliateId,
    token:            data.token,
    slug:             data.slug ?? null,
    destinationUrl:   data.destinationUrl,
    label:            data.label ?? null,
    totalClicks:      data.totalClicks ?? 0,
    totalConversions: data.totalConversions ?? 0,
    isActive:         data.isActive ?? true,
    createdAt:        Timestamp.now(),
    updatedAt:        Timestamp.now(),
  };
}

export const affiliateLinkConverter = {
  toFirestore(affiliateLink) {
    const { id, ...data } = affiliateLink;
    return data;
  },
  fromFirestore(snapshot, options) {
    const data = snapshot.data(options);
    return {
      id:               snapshot.id,
      affiliateId:      data.affiliateId,
      token:            data.token,
      slug:             data.slug ?? null,
      destinationUrl:   data.destinationUrl,
      label:            data.label ?? null,
      totalClicks:      data.totalClicks,
      totalConversions: data.totalConversions,
      isActive:         data.isActive,
      createdAt:        data.createdAt,
      updatedAt:        data.updatedAt,
    };
  },
};

// Suggested Firestore indexes:
// - affiliate_links: affiliateId ASC
// - affiliate_links: token ASC (must be unique; enforce via transaction before write)
