-- affiliate_links: Trackable links generated by affiliates with click and conversion counters.
-- See README.md for full design rationale.

CREATE TABLE affiliate_links (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    affiliate_id      UUID NOT NULL REFERENCES affiliates(id) ON DELETE CASCADE,
    token             TEXT UNIQUE NOT NULL,
    slug              TEXT,
    destination_url   TEXT NOT NULL,
    label             TEXT,
    total_clicks      INTEGER NOT NULL DEFAULT 0,
    total_conversions INTEGER NOT NULL DEFAULT 0,
    is_active         BOOLEAN NOT NULL DEFAULT true,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_affiliate_links_affiliate_id ON affiliate_links(affiliate_id);
