// transcripts: Episode transcript content in various formats.
// See README.md for full design rationale.

import { Timestamp } from "firebase/firestore";

export const TRANSCRIPT_FORMAT = /** @type {const} */ ({
  SRT: "srt",
  VTT: "vtt",
  JSON: "json",
  TEXT: "text",
});

/**
 * @typedef {Object} TranscriptDocument
 * @property {string} id
 * @property {string} episodeId - FK → episodes
 * @property {typeof TRANSCRIPT_FORMAT[keyof typeof TRANSCRIPT_FORMAT]} format
 * @property {string | null} contentUrl
 * @property {string | null} content
 * @property {string} language
 * @property {boolean} isAutoGenerated
 * @property {import("firebase/firestore").Timestamp} createdAt
 * @property {import("firebase/firestore").Timestamp} updatedAt
 */

/**
 * @param {Omit<TranscriptDocument, "id" | "createdAt" | "updatedAt">} fields
 * @returns {Omit<TranscriptDocument, "id">}
 */
export function createTranscript(fields) {
  return {
    episodeId: fields.episodeId,
    format: fields.format,
    contentUrl: fields.contentUrl ?? null,
    content: fields.content ?? null,
    language: fields.language ?? "en",
    isAutoGenerated: fields.isAutoGenerated ?? false,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  };
}

export const transcriptConverter = {
  toFirestore(doc) { return { ...doc }; },
  fromFirestore(snapshot, options) {
    const data = snapshot.data(options);
    return {
      id: snapshot.id,
      episodeId: data.episodeId,
      format: data.format,
      contentUrl: data.contentUrl ?? null,
      content: data.content ?? null,
      language: data.language,
      isAutoGenerated: data.isAutoGenerated,
      createdAt: data.createdAt,
      updatedAt: data.updatedAt,
    };
  },
};

/*
 * Suggested Firestore indexes (firestore.indexes.json):
 *
 * Composite indexes:
 *   - episodeId ASC, format ASC, language ASC
 */
