// affiliate_links: Trackable links generated by affiliates with click/conversion counters.
// See README.md for full design rationale.
use spacetimedb::Timestamp;

#[spacetimedb::table(name = affiliate_links, public)]
pub struct AffiliateLink {
    #[primary_key]
    pub id: String, // UUID

    #[index(btree)]
    pub affiliate_id: String, // UUID, FK -> affiliates.id (cascade delete)

    #[unique]
    pub token: String,

    pub slug: Option<String>,
    pub destination_url: String,
    pub label: Option<String>,
    pub total_clicks: i32,       // default 0
    pub total_conversions: i32,  // default 0
    pub is_active: bool,         // default true
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
}
