// affiliate_links: Trackable links generated by affiliates with click/conversion counters.
// See README.md for full design rationale.
import { defineTable } from "convex/server";
import { v } from "convex/values";

export const affiliateLinks = defineTable({
  affiliateId: v.id("affiliates"),
  token: v.string(),
  slug: v.optional(v.string()),
  destinationUrl: v.string(),
  label: v.optional(v.string()),
  totalClicks: v.number(),
  totalConversions: v.number(),
  isActive: v.boolean(),
  updatedAt: v.number(),
})
  .index("by_token", ["token"])
  .index("by_affiliate_id", ["affiliateId"]);
