// transcripts: episode transcripts in multiple formats with language and source metadata.
// See README.md for full design rationale.

import { defineTable } from "convex/server";
import { v } from "convex/values";

export const transcripts = defineTable({
  episodeId: v.id("episodes"),
  format: v.union(
    v.literal("srt"),
    v.literal("vtt"),
    v.literal("json"),
    v.literal("text")
  ),
  contentUrl: v.optional(v.string()),
  content: v.optional(v.string()),
  language: v.string(),
  isAutoGenerated: v.boolean(),
  updatedAt: v.number(),
}).index("by_episode_id_format_language", ["episodeId", "format", "language"]);
