// affiliate_links: Trackable links generated by affiliates for campaigns and sharing.
// See README.md for full design rationale.
const mongoose = require("mongoose");

const affiliateLinkSchema = new mongoose.Schema(
  {
    affiliate_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Affiliate",
      required: true,
    },
    token: { type: String, unique: true, required: true },
    slug: { type: String, default: null },
    destination_url: { type: String, required: true },
    label: { type: String, default: null },
    total_clicks: { type: Number, required: true, default: 0 },
    total_conversions: { type: Number, required: true, default: 0 },
    is_active: { type: Boolean, required: true, default: true },
  },
  { timestamps: { createdAt: "created_at", updatedAt: "updated_at" } }
);

affiliateLinkSchema.index({ affiliate_id: 1 });

module.exports = mongoose.model("AffiliateLink", affiliateLinkSchema);
